DROP TABLE IF EXISTS savings_transactions CASCADE;
DROP TABLE IF EXISTS savings_goals CASCADE;
DROP TABLE IF EXISTS saved_billers CASCADE;
DROP TABLE IF EXISTS bill_payments CASCADE;
DROP TABLE IF EXISTS billers CASCADE;
DROP TABLE IF EXISTS biller_categories CASCADE;
